# Setup
title:               Fact Stack
tagline:             'Unraveling interesting stories that shaped the world we live in!'
description:         ''
url:                 https://varundelft.github.io
baseurl:             'quiz-blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Varun Nair
  url:               https://twitter.com/
  email:             nair.varun1992@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
